home/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import starting, about, member, membersh, callfun, profile_view, cancelSubscription


urlpatterns = [
    # path('', starting, name='home-home'),
    path('about/', about , name='home-about'),
    path('memberships/', member , name='home-memberships'),
    path('memberships/<str:key>/', membersh , name='home-memberships-indi'),
    path('membership/<str:key>/', callfun , name='home-memberships-indiv'),
    path('profile/', profile_view , name='profileview'),
    path('cancelsub/', cancelSubscription , name='cancelsub'),
]

courses/models.py
from django.db import models
from django.urls import reverse

from home.models import Membership


class Course(models.Model):
    slug = models.SlugField()
    title = models.CharField(max_length=120)
    description = models.TextField()
    allowed_memberships = models.ManyToManyField(Membership)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('courses:detail', kwargs={'slug': self.slug})

    @property
    def lessons(self):
        return self.lesson_set.all().order_by('position')


class Lesson(models.Model):
    slug = models.SlugField()
    title = models.CharField(max_length=120)
    course = models.ForeignKey(Course, on_delete=models.SET_NULL, null=True)
    position = models.IntegerField()
    video_url = models.CharField(max_length=200)
    thumbnail = models.ImageField()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('courses:lesson-detail',
                       kwargs={
                           'course_slug': self.course.slug,
                           'lesson_slug': self.slug
                       })

home/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from django.conf import settings
from django.db.models.signals import post_save

from datetime import datetime
import stripe
stripe.api_key = settings.STRIPE_SECRET_KEY


MEMBERSHIP_CHOICES = (
    ('Enterprise', 'ent'),
    ('Professional', 'pro'),
    ('Free', 'free')
)


class Membership(models.Model):
    slug = models.SlugField()
    membership_type = models.CharField(
        choices=MEMBERSHIP_CHOICES,
        default='Free',
        max_length=30)
    price = models.IntegerField(default=15)
    stripe_plan_id = models.CharField(max_length=40)

    def __str__(self):
        return self.membership_type


class UserMembership(models.Model):
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    stripe_customer_id = models.CharField(max_length=40)
    membership = models.ForeignKey(
        Membership, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return self.user.username


def post_save_usermembership_create(sender, instance, created, *args, **kwargs):
    user_membership, created = UserMembership.objects.get_or_create(
        user=instance)


    if user_membership.stripe_customer_id is None or user_membership.stripe_customer_id == '':
        new_customer_id = stripe.Customer.create(email=instance.email)
        free_membership = Membership.objects.get(membership_type='Free')
        user_membership.stripe_customer_id = new_customer_id['id']
        user_membership.membership = free_membership
        user_membership.save()


post_save.connect(post_save_usermembership_create,
                  sender=settings.AUTH_USER_MODEL)


class Subscription(models.Model):
    user_membership = models.ForeignKey(
        UserMembership, on_delete=models.CASCADE)
    stripe_subscription_id = models.CharField(max_length=40)
    active = models.BooleanField(default=True)

    def __str__(self):
        return self.user_membership.user.username

    @property
    def get_created_date(self):
        subscription = stripe.Subscription.retrieve(
            self.stripe_subscription_id)
        return datetime.fromtimestamp(subscription.created)

    @property
    def get_next_billing_date(self):
        subscription = stripe.Subscription.retrieve(
            self.stripe_subscription_id)
        return datetime.fromtimestamp(subscription.current_period_end)

home/forms.py
from django import forms

home/views.py
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404, reverse
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.views.generic import ListView, CreateView, UpdateView, DetailView, DeleteView
from django.contrib.auth.models import User
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from .models import Membership, UserMembership, Subscription
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required

import stripe

# Create your views here.
def starting(request):
    return render(request,'home/starting.html',{})

def about(request):
    return render(request,'home/about.html')

@login_required
def member(request):
    object = Membership.objects.all()
    context = { 'object_list':object,
                'current_membership':get_user_membership(request).membership
    }
    print(context)
    return render(request,'home/membership.html',context)

def get_user_membership(request):
    user_membership_qs = UserMembership.objects.filter(user=request.user)
    if user_membership_qs.exists():
        return user_membership_qs.first()
    return None

@login_required
def membersh(request,key):
    object = Membership.objects.filter(membership_type=key)
    publishKey = settings.STRIPE_PUBLISHABLE_KEY
    user_membership = get_user_membership(request)
    stripeprice = object[0].price * 100
    context = { 'selected_membership':object,
                'publishKey': publishKey,
                'stripeprice':stripeprice }
    return render(request,'home/membershipindi.html',context)


def get_user_subscription(request):
    user_subscription_qs = Subscription.objects.filter(
        user_membership=get_user_membership(request))
    if user_subscription_qs.exists():
        user_subscription = user_subscription_qs.first()
        return user_subscription
    return None


@login_required
def updateTransactionRecords(request, subscription_id, selected_membership):
    user_membership = get_user_membership(request)
    user_membership.membership = selected_membership
    user_membership.save()

    sub, created = Subscription.objects.get_or_create(
        user_membership=user_membership)
    sub.stripe_subscription_id = subscription_id
    sub.active = True
    sub.save()

    try:
        del request.session['selected_membership_type']
    except:
        pass

    messages.info(request, 'Successfully created {} membership'.format(
        selected_membership))
    return redirect(reverse('home-memberships'))

@login_required
def cancelSubscription(request):
    user_sub = get_user_subscription(request)

    if user_sub.active is False:
        messages.info(request, "You dont have an active membership")
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

    sub = stripe.Subscription.retrieve(user_sub.stripe_subscription_id)
    sub.delete()

    user_sub.active = False
    user_sub.save()

    free_membership = Membership.objects.get(membership_type='Free')
    user_membership = get_user_membership(request)
    user_membership.membership = free_membership
    user_membership.save()


    return redirect(reverse('profileview'))

@login_required
def callfun(request,key):
    if request.method == "POST":
        object = Membership.objects.filter(membership_type=key)
        publishKey = settings.STRIPE_PUBLISHABLE_KEY
        user_membership = get_user_membership(request)
        selected_membership = Membership.objects.get(membership_type=key)
        token = request.POST['stripeToken']

        # UPDATE FOR STRIPE API CHANGE 2018-05-21

        '''
        First we need to add the source for the customer
        '''
        customer = stripe.Customer.retrieve(user_membership.stripe_customer_id)
        customer.source = token # 4242424242424242
        customer.save()

        '''
        Now we can create the subscription using only the customer as we don't need to pass their
        credit card source anymore
        '''

        subscription = stripe.Subscription.create(
            customer=user_membership.stripe_customer_id,
            items=[
                { "plan": selected_membership.stripe_plan_id },
            ]
        )
        updateTransactionRecords(request,subscription.id,selected_membership)
        return redirect(reverse('home-memberships'))

@login_required
def profile_view(request):
    user_membership = get_user_membership(request)
    user_subscription = get_user_subscription(request)
    context = {
        'user_membership': user_membership,
        'user_subscription': user_subscription
    }
    return render(request, "users/profile.html", context)

home/templates/home/about.html
{% extends './basic.html' %}

{% block main %}
<br>
<br>
<br>
   <!-- Card -->
<div class="card">

  <!-- Card image -->

  <!-- Card content -->
  <div class="card-body">

    <!-- Title -->
    <h4 class="card-title">About TravelShare</a></h4>
    <!-- Text -->
    <p class="card-text">TravelShare is a travelling experience sharing site</p>
  </div>

</div>

{% endblock main %}

home/templates/home/basic.html
<!DOCTYPE html><html lang="en">
<head>
<meta charset="UTF-8">
<title>InstaShare</title><!-- Font Awesome -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"><!-- Bootstrap -->
<link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css" rel="stylesheet"> 
<!-- Material Design for Bootstrap --><link href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.5.16/css/mdb.min.css" rel="stylesheet">
</head>
<body>
<!--Navbar-->
<nav class="navbar navbar-expand-lg navbar-dark primary-color">

  <!-- Navbar brand -->
  <a class="navbar-brand" href="#">Navbar</a>

  <!-- Collapse button -->
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav"
    aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <!-- Collapsible content -->
  <div class="collapse navbar-collapse" id="basicExampleNav">

    <!-- Links -->
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href={% url 'courses-home' %}>Home
          <span class="sr-only">(current)</span>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href={% url 'home-memberships' %}>Membership</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href={% url 'home-about' %}>About</a>
      </li>


    </ul>
    <!-- Links -->

    <form class="form-inline">
      <div class="md-form my-0">
      <ul class="navbar-nav mr-auto">
      {% if user.is_authenticated %}
       <li class="nav-item">
        <a class="nav-link" href="{% url 'profileview' %}">Profile</a>
      </li>
       <li class="nav-item">
        <a class="nav-link" href="{% url 'users-logout' %}">Logout</a>
      </li>
      {% else %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'users-register' %}">Register</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'users-login' %}">Login</a>
      </li>
      {% endif %}
      </ul>
      </div>
    </form>
  </div>
  <!-- Collapsible content -->

</nav>
<!--/.Navbar-->
<div class="container">
          {% if messages %}
            {% for message in messages %}
              <div class="alert alert-{{ message.tags }}">
                {{ message }}
              </div>
            {% endfor %}
          {% endif %}
{% block main %}
{% endblock main %}
</div>
<!-- jQuery --><script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<!-- Popper.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
<!-- Bootstrap --><script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.min.js"></script>
<!-- Material Design for Bootstrap --><script src="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.5.16/js/mdb.min.js"></script>
<script>  new WOW().init();</script>
</body>
</html>

home/templates/home/membership.html
{% extends './basic.html' %}

{% block main %}
<br>
<br>
<br>

<div class="container">
	<h1>Select a membership</h1>
	<div class="row">
		{% for object in object_list %}
		<div class="col-sm-4 col-md-4">
			<h2>{{ object.membership_type }}</h2>
			<p>Price: ${{ object.price }}<small>/month</small></p>
			<h4>Included Courses</h4>
			<ul>
				{% for course in object.course_set.all %}
					<li>{{ course.title }}</li>
				{% endfor %} 
			</ul>
			{% if object.membership_type != 'Free' %}
			<form method="POST" action={% url 'home-memberships-indi' object.membership_type %}>
				{% csrf_token %}
				{% if object != current_membership %}
					<button class="btn btn-warning">Select</button>
				{% else %}
					<small>This is your current membership</small>
				{% endif %}
				<input type="hidden" name="membership_type" value="{{ object.membership_type }}">
			</form>			
			{% endif %}	
		</div>
		{% endfor %}
	</div>
</div> 


{% endblock main %}

home/templates/home/membershipindi.html
{% extends './basic.html' %}
{% load static %}

{% block main %}
 <link rel="stylesheet" type="text/css" href="{% static 'home/css/checkout.css' %}">
<br>
<br>
<br>



<div class="container">
	<div class="row">
		<h1>Payment</h1>
		<div class="col-sm-4 col-md-4">
			<p>Selected membership: {{ selected_membership.0 }}</p>
			<p>Price: <strong>${{ selected_membership.0.price }}</strong><small>/month</small></p>


<div id="collapseStripe" class="wrapper">
  <script src="https://js.stripe.com/v3/"></script>

  <!-- can't do this -->
  <!-- <script src="{% static 'js/stripeV3.js' %}"></script> -->
  {% if selected_membership.0.price != 0 and selected_membership.0 != current_membership%}
 <form action={% url 'home-memberships-indiv' selected_membership.0 %} method="post">
        {% csrf_token %}
         <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                        data-key="{{ publishKey }}"
                        data-description="Monthly Charge"
                        data-amount="{{ stripeprice }}"
                        data-locale="auto"></script>
    </form>
{% endif %}
  
  </div>
  
</div>

<div id="stripe-token-handler" class="is-hidden">Success! Got token: <span class="token"></span></div>


		</div>
	</div>
</div>


<!-- script for the stripe form -->
<script src="{% static 'home/js/checkout.js' %}"></script>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>

<!-- script for toggling display of the form -->
<script type="text/javascript">
    function toggleDisplay() {
      var x = document.getElementById("collapseStripe");
      if (x.style.display === "none") {
          x.style.display = "block";
      } else {
          x.style.display = "none";
      }
    };
</script>


{% endblock main %}

home/templates/home/starting.html
{% extends './basic.html' %}

{% block main %}
<br>
<br>
<br>
{% for post in posts %}
   <!-- Card -->
<div class="card">

  <!-- Card image -->

  <!-- Card content -->
  <div class="card-body">

    <!-- Title -->
    <h4 class="card-title"><a href={% url 'home-detailpost' post.id %}>{{ post.title }}</a></h4>
    <h6 class="card-title"><a href={% url 'home-user' post.author %}>{{ post.author }}</a></h6>
    <!-- Text -->
    <p class="card-text">{{ post.content }}</p>
  </div>

</div>
<!-- Card -->
{% endfor %}

<br>
<br>
 {% if is_paginated %}

      {% if page_obj.has_previous %}
        <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>
      {% endif %}

      {% for num in page_obj.paginator.page_range %}
        {% if page_obj.number == num %}
          <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
        {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
          <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
        {% endif %}
      {% endfor %}

      {% if page_obj.has_next %}
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
      {% endif %}

    {% endif %}

{% endblock main %}